name: Build PBR

on:
  schedule:
    - cron: "2 */8 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: download cidr
      run: |
        chmod +x ros-dpbr.sh
        ./ros-dpbr.sh
    - name: Commit files
      run: |
        git config --local user.email "ctt727@github.com"
        git config --local user.name "ctt727"
        git commit -a -m "Add changes"        
    - name: Commit & Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: master
